#!/usr/bin/env ruby
require "fileutils"
include FileUtils

cd "build" do
  mkdir "icon.iconset"
  Dir["../img/*.png"].each do |file|
    m = file.match(%r{Screenhive-(\d+)px[.]png})
    size = m[1].to_i
    cp file, "icon.iconset/icon_#{size}x#{size}.png"
  end
  system "iconutil", "-c", "icns", "icon.iconset"
  rm_r "icon.iconset"
end
